FROM webhippie/python:latest-arm64v8

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Elasticsearch Curator" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/curator"]

RUN apk update && \
  apk upgrade && \
  pip3 install -U pip elasticsearch-curator && \
  rm -rf /var/cache/apk/*
